siasdo/urls.py
# coding=utf8
# -*- coding: utf8 -*-
# vim: set fileencoding=utf8 :
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from siasdo.site_siasdo import views
from siasdo.site_siasdo import forms
from django.contrib.auth.decorators import login_required
from siasdo.usuarios import views as p 
#from siasdo.estados import views as teste
urlpatterns = patterns('',
    # Examples:
     url(r'^$', 'siasdo.site_siasdo.views.home', name='home'),
     url(r'^cadastre-se/$',views.cadastre_se,name = 'cadastre_se'),
     url(r'^profissionais/$', 'siasdo.site_siasdo.views.profissionais', name='profissionais'),
     url(r'^pacientes/$', 'siasdo.site_siasdo.views.pacientes', name='pacientes'),
     url(r'^password/$', 'siasdo.site_siasdo.views.password', name='password'),
     url(r'^success/$', 'siasdo.site_siasdo.views.success', name='success'),
     url(r'^login/$', 'siasdo.site_siasdo.views.LoginRequest', name='login'),
     # url(r'^loginproblem/$',views.login_problem,name = 'problem_login'),
     url(r'^search/prof/$', 'siasdo.site_siasdo.views.search_page',name = 'search'),
     url(r'^search/profissional/(?P<slugprof>.*)/$','siasdo.site_siasdo.views.single_profissional',name = 'single_profissional'), 
     url(r'^error_page/$', 'siasdo.site_siasdo.views.error_page', name ='error_page'),
     url(r'^avalie/$', 'siasdo.site_siasdo.views.avalie', name ='avalie'),
     #url(r'^index_logado/$', 'siasdo.site_siasdo.views.index_logado', name ='index_logado'),
     url(r'^resend_email/$',views.resend_email,name = 'resend_email'),
     
     
     #url(r'^profile_profissional/edit_photo/$','siasdo.site_siasdo.views.changephoto',name ="edit_photo"),

     #url para view profile que redirecionar para as devidas paginas
     url(r'^profile/$', 'siasdo.site_siasdo.views.profile',name = 'profile'),
     url(r'^profile/search/$','siasdo.site_siasdo.views.profile_redirect_search',name = 'profile_search'),
     url(r'^logout/$', 'siasdo.site_siasdo.views.LogoutRequest',name = 'logout'),
     #urls dos perfis de profissionais
     url(r'^register/success_register/$','siasdo.site_siasdo.views.success_register',name = 'success_register'),
     url(r'^accounts/confirm/(?P<activation_key>\w+)/$','siasdo.site_siasdo.views.register_confirm_email', name = 'confirm_email'),
     
     url(r'^profile_profissional/delete_consultas/(?P<id_consulta>\d+)/$',views.delete_consultas_profissional,name = 'delete_consultas_prof'),
     url(r'^profile_profissional/add_servico/$',views.add_servico,name = 'add_servico'),
     url(r'^profile_profissional/delete_servico/(?P<pk_servico>\d+)/$',views.delete_servico,name = 'delete_servico'),
      url(r'^profile_profissional/move_consulta/(?P<id_consulta>\d+)/$',views.move_consultas,name = 'move'),
     url(r'^profissional/curriculo/(?P<idprof>\d+)/$',views.get_curriculo,name = 'get_curriculo'),
     url(r'^profile_profissional/persons/$','siasdo.site_siasdo.views.profile_profissional_list',name = 'profile_persons'),
     url(r'^profile_profissional/search/$','siasdo.site_siasdo.views.profile_profissional_search',name = 'profile_profissional_search'),
     url(r'^profile_profissional/delete_rote/(?P<id_rote>\d+)/$','siasdo.site_siasdo.views.delete_rote',name = 'delete_rote'),
     url(r'^profile_profissional/delete_rote_page/$','siasdo.site_siasdo.views.delete_rote_page',name = 'delete_rote_page'),
     url(r'^profile_profissional/add_rota/$','siasdo.site_siasdo.views.add_rote',name = 'add_rota'),
     url(r'^profile_profissional/$','siasdo.site_siasdo.views.profile_profissional',name = 'profile_profissional'),
     url(r'^profile_profissional/edit_settings/$',views.EditSettingsProfissional,name = 'edit_settings_profissional'),
     url(r'^profile_profissional/edit_settings/success/$','siasdo.site_siasdo.views.success_config_profile',name = 'succes_config'),
     url(r'^profile_profissional/confirm_query/(?P<id_consulta>\d+)/$',views.confirmar_consulta,name = 'confirmar'),
     url(r'^profile_profissional/edit_senha/$','django.contrib.auth.views.password_change',{'template_name':
          'alterar_senha.html','post_change_redirect':'/profile_profissional/edit_senha/success/','password_change_form':forms.PasswordChangeForm},name = 'edit_senha'),
     url(r'^profile_profissional/edit_senha/success/$','django.contrib.auth.views.password_change_done',
          {'template_name':'change_password_succes.html'}),
     url(r'^profile_profissional/consultas_nao_confirmadas/$',views.consultas_profissional_nao_confirmadas,name = 'consultas_nao_confirmadas'),
     url(r'^profile_profissional/change_foto/$',views.change_foto,name = 'change_foto'),
     #url dos perfis dos pacientes
     url(r'^profile_paciente/delete_consultas/(?P<id_consulta>\d+)$',views.delete_consultas_paciente,name = 'delete_consultas_paciente'),
     url(r'^profile_paciente/$', 'siasdo.site_siasdo.views.profile_paciente', name = 'profile_paciente'),
     url(r'^profile_paciente/edit_settings/$',views.EditSettingsPaciente,name = 'edit_settings_paciente'),
     url(r'^profile_paciente/search/$','siasdo.site_siasdo.views.profile_paciente_search',name = 'profile_paciente_search'),
     url(r'^profile_paciente/minhas-consultas/$',views.minhas_consultas,name = 'minhas_consultas'),
     url(r'^profile_paciente/edit_senha/$','django.contrib.auth.views.password_change',{'template_name':
          'alterar_senha2.html','post_change_redirect':'/profile_paciente/edit_senha/success/',
          'password_change_form':forms.PasswordChangeForm},name = 'edit_senha_paciente' ),
     url(r'^profile_paciente/edit_senha/success/','django.contrib.auth.views.password_change_done',name = 'success_senha_paciente'),
     url(r'^search/$', 'siasdo.site_siasdo.views.search', name = 'search'),
    
     #urls para recuperaçao de senha via email
     url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done',{'template_name':'success.html'},name='password_reset_done'),
     url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset',{'template_name':'forgot_password.html', 'password_reset_form':forms.EmailSentForm},name = 'password_reset'),
     url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',{'template_name':'confirm_email.html'},name = 'password_reset_confirm'),
     url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',{'template_name':'success_password.html'},name ='password_reset_complete'),
     url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$','django.contrib.auth.views.password_reset_confirm',{'template_name':'confirm_email.html',
          'set_password_form':forms.SetPasswordForm},name='password_reset_confirm'),   
     #urls para recuperacao de senha via email
     #url(r'^config_profile/$', 'siasdo.site_siasdo.views.config_profile', name='config_profile'),
     #url(r'^message/$', 'siasdo.site_siasdo.views.message', name='message'),
     # url(r'^alterar_senha/$','siasdo.site_siasdo.views.alterar_senha', name = 'alterar_senha'),
     #url(r'^blog/', include('blog.urls')),
    #url(r'^teste/',teste.teste,name = 'teste'),
    url(r'^get_bairros/',views.get_bairros,name = 'get'),   
    url(r'^admin/', include(admin.site.urls)),
    )

siasdo/site_siasdo/models.py
from django.db import models

# Create your models here.

siasdo/site_siasdo/forms.py
# coding=utf8
# -*- coding: utf8 -*-
# vim: set fileencoding=utf8 :
from django import forms
from django.forms import ModelForm	
from siasdo.usuarios.models import Profissional,Paciente,Area,Rota,Bairro,Servicos,Cidade
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from collections import OrderedDict
from django.contrib.auth import authenticate
from django.contrib.auth.forms import SetPasswordForm,PasswordResetForm
from django.contrib import messages

class ProfissionalForm(ModelForm):
	
	class Meta: 
		model = Profissional
		exclude = ('user','activation_key','key_expires')
		fields = ['nome','email','senha','senha1','area','cep','cidade','bairro','endereco'
		,'complemento','foto',]
		
	
	nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Nome:")
	#username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label = '*Usuario')
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','type':'email'}),label="*Email:")
	area = forms.ModelChoiceField( widget=forms.Select(attrs = {'required':'true'}),queryset = Area.objects.all(),label="*Area:")
	cep = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','OnkeyPress':'formatar("#####-###", this)','maxlength':'9'}))
	#estado = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','maxlength':'2'}),label="*Estado(sigla)")
	cidade = forms.ModelChoiceField( widget=forms.Select(attrs = {'required':'true'}),queryset = Cidade.objects.all(),label="*Cidade:") #forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Cidade")
	endereco = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Endereço")
	#bairro = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Bairro:")
	bairro = forms.ModelChoiceField(widget=forms.Select(attrs = {'required':'true'}),queryset = Bairro.objects.all(),label="*Bairro:")
	complemento = forms.CharField(widget = forms.Textarea(attrs={'class':'form-control'}),label="Complemento:", required = False)
	foto = forms.ImageField(label="Foto(Opcional)", required = False)
	senha = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control','required':'true'}),label="*Senha")
	senha1 = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control','required':'true'}),label="*Confirme a senha", required = False)
	numero = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control','required':'true'}),label = "*Telefone celular")
	curriculo = forms.Field(widget =forms.FileInput(attrs = {'accept':'application/pdf'}),required = False,label = "Curriculo\n(Somente pdf)")	
	def clean_email(self):
		try:
			user = User.objects.get(username = self.cleaned_data['email'])
		except User.DoesNotExist:
			return self.cleaned_data['email']
		raise forms.ValidationError('Email já cadastrado, escolha outro')



	def clean_senha1(self):
		if self.cleaned_data['senha'] != self.cleaned_data['senha1']:
			raise forms.ValidationError('As senhas nao correspondem!')
		elif len(self.cleaned_data['senha1'])<6:
			raise forms.ValidationError('Senha deve conter no mínimo 6 caracteres')
		return self.cleaned_data['senha']
		
	def foto_url(self):
		if self.foto and hasattr(self.cleaned_data['foto'], 'url'):
			return self.cleaned_data['foto']
		else:
			return 'siasdo/usuarios/upload_files/profile_none/images.jpeg'
	def clean_numero(self):
		numero = self.cleaned_data['numero']
		try:
			if long(numero) and not numero.isalpha():
				min_lenght = 7
				max_lenght = 11
				ph_lenght = str(numero)
				if len(ph_lenght)<min_lenght or len(ph_lenght)>max_lenght:
					raise forms.ValidationError('Tamanho inválido!')
		except(ValueError,TypeError):
			raise forms.ValidationError('digite um número válido!')
		return numero
	import os

	
	def clean_curriculo(self):
		curriculo = self.cleaned_data['curriculo']
		types = ['pdf']
		content_type = str(curriculo).split('.')[-1]
		if curriculo != None:
			if content_type in types:
				if curriculo._size > 2621440:
					raise forms.ValidationError('Tamanho acima do permitido')
				return curriculo
			raise forms.ValidationError('Formato inválido, somente pdf')

	def clean_foto(self):
		foto = self.cleaned_data['foto']
		types = ['jpeg','jpg','png','gif']
		content_type = str(foto).split('.')[-1]
		if foto != None:
			if content_type in types:
				if foto._size > 5242880:
					raise forms.ValidationError('tamanho acima do permitido')
				return foto
			raise forms.ValidationError('Formatos aceitos : "jpg", "jpeg", "png", "gif"')
	
	def clean_cep(self):
		import re
		pattern1 = r'\d{5}-\d{3}'
		cep = self.cleaned_data['cep']
		if re.match(pattern1,str(cep)) is None:
			raise forms.ValidationError('formato de cep inválido')
		return cep

		

class PacienteForm(ModelForm)	:
	class Meta:	
		model = Paciente
		exclude = ('user','slug','activation_key','key_expires','foto')
		fields = ['nome','email','senha','senha1','cep','cidade','bairro','endereco','complemento']
	#username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label = '*Usuario') 
	nome = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Nome:")
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','type':'email'}),label="*Email:")
	cep = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','OnkeyPress':'formatar("#####-###", this)', 'maxlength':'9'}),label="*Cep")
	#estado = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Estado")
	cidade = forms.ModelChoiceField( widget=forms.Select(attrs = {'required':'true'}),queryset = Cidade.objects.all(),label="*Cidade:")#forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Cidade")
	endereco = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Endereço")
	#bairro = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','required':'true'}),label="*Bairro:")
	bairro = forms.ModelChoiceField(widget=forms.Select(attrs = {'required':'true'}),queryset = Bairro.objects.all(),label="*Bairro:")#forms.ModelChoiceField( widget=forms.Select(attrs = {'required':'true'}),queryset = Bairro.objects.all(),label="*Bairro:")
	complemento = forms.CharField(widget = forms.Textarea(attrs={'class':'form-control'}),label="Complemento:",required = False)
	senha = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control','required':'true'}),label="*Senha")
	senha1 = forms.CharField(widget = forms.PasswordInput(attrs = {'class':'form-control','required':'true'}),label = "*Confirme sua Senha")

	def clean_email(self):
		try:
			user = User.objects.get(username = self.cleaned_data['email'])
		except User.DoesNotExist:
			return self.cleaned_data['email']
		raise forms.ValidationError('Email já cadastrado, escolha')
		


	def clean_senha1(self):
		if self.cleaned_data['senha'] != self.cleaned_data['senha1']:
			raise forms.ValidationError('As senhas nao correspondem!')
		elif len(self.cleaned_data['senha1'])<6:
			raise forms.ValidationError('Senha deve conter no mínimo 6 caracteres')
		return self.cleaned_data['senha']
	def clean_cep(self):
		import re
		pattern1 = r'\d{5}-\d{3}'
		cep = self.cleaned_data['cep']
		if re.match(pattern1,str(cep)) is None:
			raise forms.ValidationError('formato de cep inválido')
		return cep




class LoginForm(forms.Form):
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','required':'true','type':'email','placeholder':'Email'}),label="*Email:")
	senha = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control','required':'true','placeholder':'Senha'}),label="*Senha")
	remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(),label = "Lembre de mim")
	def __init__(self, *args, **kwargs):
		self.auth = None
		super(LoginForm,self).__init__(*args,**kwargs)


	def clean(self):
		username = self.cleaned_data['email']
		password = self.cleaned_data['senha']
		self.auth = authenticate(username = username,password = password)
		if self.auth is None:
			raise forms.ValidationError('email ou senha invalidos')
		
	
	def get_user(self):
		return self.auth
	

	

#falta validar o formulario
class EditSettingFormProfissional(ModelForm):
	class Meta:
		model = Profissional
		exclude = ('user','email','slug','key_expires','activation_key','foto','tem_certificado','curriculo',)

	def __init__(self,*args,**kwargs):
		self.user = kwargs.pop('user', None)
		super(EditSettingFormProfissional,self).__init__(*args,**kwargs)

	nome = forms.CharField(widget = forms.TextInput(attrs ={'class':'form-control','placeholder':'Nome','required':'true'}))
	cep = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Cep','required':'true','OnkeyPress':'formatar("#####-###", this)', 'maxlength':'9'}))
	#estado = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Estado','required':'true'}))
	cidade = forms.ModelChoiceField( widget=forms.Select(attrs = {'class':'form-control','placeholder':'Endereco','required':'true'}),queryset = Cidade.objects.all(),label="*Cidade:")#forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Cidade','required':'true'}))
	endereco = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Endereco','required':'true'}))
	bairro = forms.ModelChoiceField(widget=forms.Select(attrs = {'class':'form-control','required':'true'}),queryset = Bairro.objects.all())

siasdo/site_siasdo/templates/config_profile_paciente.html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> 
<html lang="en"> <!--<![endif]-->  
<head>
    <title>Siasdo</title>
    <!-- Meta -->
    <link rel="shortcut icon" href="{{STATIC_URL}}assets/images/logosm.ico" type="image/x-icon">
    <link rel="icon" href="{{STATIC_URL}}assets/images/logosm.ico" type="image/x-icon">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">     
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'> 
    <!-- Global CSS -->
    <link rel="stylesheet" href="{{STATIC_URL}}assets/plugins/bootstrap/css/bootstrap.css">
    <!-- Plugins CSS -->    
    <link rel="stylesheet" href="{{STATIC_URL}}assets/plugins/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="{{STATIC_URL}}assets/plugins/prism/prism.css">
    <!-- animsition CSS -->
    <link rel="stylesheet" href="../dist/css/animsition.min.css">
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{{STATIC_URL}}assets/css/styles.css">
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">
        function populateFruitVariety() {
            $.getJSON('http://siasdo.com.br/get_bairros/', {cidade:$('#id_cidade').val()}, function(data) {
                var select = $('#id_bairro');
                var options = select.prop('options');
                $('option', select).remove();
                $.each(data, function(key, value) {
                    //options[options.length] = new Option(array['bairro']);
                   $('#id_bairro')
         .append($("<option></option>")
         .attr("value",value.id_bairro)
         .text(value.unicode)); 
                    
                    });
        

               });
                }
        $(document).ready(function() {
            populateFruitVariety();
            $('#id_cidade').change(function() {
                populateFruitVariety();
            });
        });



   </script>
   <script>
function formatar(mascara, documento){
  var i = documento.value.length;
  var saida = mascara.substring(0,1);
  var texto = mascara.substring(i)
  
  if (texto.substring(0,1) != saida){
            documento.value += texto.substring(0,1);
  }
  
}
</script>
</head> 
<body>
    <header class="header navbar-fixed-top">
        <div class="container">            
            <h1 class="logo pull-left">
                <a href="/">
                    <span class="logo-title">SIASDO</span>
                </a>
            </h1>
            <nav id="main-nav" class="main-nav navbar-right" role="navigation">
                <div class="navbar-header">
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="glyphicon glyphicon-align-justify"></span>
                    </button>
                </div>         
                <div class="navbar-collapse collapse" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active nav-item sr-only"><a class="scrollto" href="#promo">Home</a></li>
                        <li class="nav-item"><a href="/profile_paciente/">Voltar</a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <div class="container-fluid offset-header">
        <div class="container"> 
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 style="color:black;" class="text-center">Configurações</h4>
                        </div>
                        <div class="panel-body">
                            <p class="text-center">Aqui você pode alterar suas informações.</p>
                            <hr>
                            <div class="col-md-offset-3 col-md-6 text-center">
                                <form method="post">
                                    {% csrf_token %}
                                    {% if flag_save %}
                                        <div class="alert alert-error">
                                            <button type="button" class="close" data-dismiss="alert">x</button>
                                            Dados Atualizados!  
                                        </div>
                                    {%endif%}
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-user"></i>
                                        </span>
                                        {{form.nome}}
                                    </div>   
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.cep}}
                                    </div>
                                    <!-- <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.estado}}
                                    </div> -->
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.cidade}}
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.bairro}}
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.endereco}}
                                    </div>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-map-marker"></i>
                                        </span>
                                        {{form.complemento}}
                                    </div>
                                    <div class="col-sm-12 controls">
                                        <button type="submit" href="#" class="btn btn-cta-secondary btn-lg">Mudar</button>
                                    </div>
                                </form>
                                <script type="text/javascript" >
                                    $(document).ready(function() {

                                        function limpa_formulário_cep() {
                                            // Limpa valores do formulário de cep.
                                            $("#").val("");
                                            $("#").val("");
                                            $("#").val("");
                                            $("#").val("");
                                        }
                                        
                                        //Quando o campo cep perde o foco.
                                        $("#id_cep").blur(function() {

                                            //Nova variável com valor do campo "cep".
                                            var cep = $(this).val();

                                            //Verifica se campo cep possui valor informado.
                                            if (cep != "") {

                                                //Expressão regular para validar o CEP.
                                                var validacep = /^[0-9]{5}-?[0-9]{3}$/;

                                                //Valida o formato do CEP.
                                                if(validacep.test(cep)) {

                                                    //Preenche os campos com "..." enquanto consulta webservice.
                                                    $("#id_endereco").val("...")
                                                    $("#").val("...")
                                                    $("#").val("...")
                                                    $("#").val("...")
                                                    //$("#ibge").val("...")

                                                    //Consulta o webservice viacep.com.br/
                                                    $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                                                        if (!("erro" in dados)) {
                                                            //Atualiza os campos com os valores da consulta.
                                                            $("#id_endereco").val(dados.logradouro);
                                                            $("#").val(dados.bairro);
                                                            $("#").val(dados.localidade);
                                                            $("#").val(dados.uf);
                                                            //$("#ibge").val(dados.ibge);
                                                        } //end if.
                                                        else {
                                                            //CEP pesquisado não foi encontrado.
                                                            limpa_formulário_cep();
                                                            alert("CEP não encontrado.");
                                                        }
                                                    });
                                                } //end if.
                                                else {
                                                    //cep é inválido.
                                                    limpa_formulário_cep();
                                                    alert("Formato de CEP inválido.");
                                                }
                                            } //end if.
                                            else {
                                                //cep sem valor, limpa formulário.
                                                limpa_formulário_cep();
                                            }
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <!-- Javascript -->          
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/jquery-migrate-1.2.1.min.js"></script>    
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/jquery.easing.1.3.js"></script>   
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/bootstrap/js/bootstrap.min.js"></script>     
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/jquery-scrollTo/jquery.scrollTo.min.js"></script> 
    <script type="text/javascript" src="{{STATIC_URL}}assets/plugins/prism/prism.js"></script>    
    <script type="text/javascript" src="{{STATIC_URL}}assets/js/main.js"></script> 
</body>
</html>